var configData = {
	img:[
		{
			id:"mapBg",
			src:"../src/images/mapBg.jpg"
		},
		{
			id:"pos_one",
			src:"../src/images/pos_one.png"
		},
		{
			id:"pos_two",
			src:"../src/images/pos_two.png"
		},
		{
			id:"init_boat",
			src:"../src/images/init_boat.png"
		},
		{
			id:"init_boat",
			src:"../src/images/init_boat.png"
		},
		{
			id:"init_boy",
			src:"../src/images/init_boy.png"
		},
		{
			id:"getBoat",
			src:"../src/images/getBoat.png"
		},
		{
			id:"end",
			src:"../src/images/end.png"
		},
		{
			id:"left",
			src:"../src/images/left.png"
		},
		{
			id:"right",
			src:"../src/images/right.png"
		}
	]
};